package utils

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"sync"
	"time"

	"github.com/golang-jwt/jwt/v5"
)

var (
	autoGeneratedSecret []byte
	once                sync.Once
)

// generateRandomSecret membuat 32-byte kunci acak yang aman secara kriptografi
func generateRandomSecret() []byte {
	bytes := make([]byte, 32)
	if _, err := rand.Read(bytes); err != nil {
		// Fallback jika crypto/rand gagal
		return []byte("fallback_super_secret_jwt_key_123456789")
	}
	return []byte(hex.EncodeToString(bytes))
}

// getJWTSecret mengambil secret key dari environment variable JWT_SECRET di .env.
// Jika kosong, aplikasi akan OTOMATIS meng-generate kunci acak yang aman.
func getJWTSecret() []byte {
	secret := os.Getenv("JWT_SECRET")
	if secret != "" {
		return []byte(secret)
	}

	// Otomatis generate kunci acak sekali saat aplikasi pertama kali berjalan
	once.Do(func() {
		autoGeneratedSecret = generateRandomSecret()
		fmt.Println("⚡ Info: JWT_SECRET tidak diisi di .env. Menggunakan kunci acak otomatis (Auto-Generated Secret Key).")
	})

	return autoGeneratedSecret
}

// CustomClaims memuat payload data di dalam JWT token.
type CustomClaims struct {
	UserID    uint   `json:"user_id"`
	Email     string `json:"email"`
	Role      string `json:"role"`
	TokenType string `json:"token_type"` // "access" atau "refresh"
	jwt.RegisteredClaims
}

// GenerateAccessToken membuat Access Token berdurasi SINGKAT (15 Menit).
func GenerateAccessToken(userID uint, email string, role string) (string, error) {
	if role == "" {
		role = "admin"
	}
	claims := CustomClaims{
		UserID:    userID,
		Email:     email,
		Role:      role,
		TokenType: "access",
		RegisteredClaims: jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(time.Now().Add(15 * time.Minute)), // 15 Menit
			IssuedAt:  jwt.NewNumericDate(time.Now()),
		},
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	return token.SignedString(getJWTSecret())
}

// GenerateRefreshToken membuat Refresh Token berdurasi PANJANG (7 Hari).
func GenerateRefreshToken(userID uint, email string) (string, error) {
	claims := CustomClaims{
		UserID:    userID,
		Email:     email,
		TokenType: "refresh",
		RegisteredClaims: jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(time.Now().Add(7 * 24 * time.Hour)), // 7 Hari
			IssuedAt:  jwt.NewNumericDate(time.Now()),
		},
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	return token.SignedString(getJWTSecret())
}

// GenerateToken backward compatibility helper
func GenerateToken(userID uint, email string, role string) (string, error) {
	return GenerateAccessToken(userID, email, role)
}

// ValidateToken memverifikasi JWT token dan mengembalikan CustomClaims jika valid.
func ValidateToken(tokenString string) (*CustomClaims, error) {
	token, err := jwt.ParseWithClaims(tokenString, &CustomClaims{}, func(t *jwt.Token) (interface{}, error) {
		// Validasi algoritma signing
		if _, ok := t.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, errors.New("metode signing token tidak valid")
		}
		return getJWTSecret(), nil
	})

	if err != nil {
		return nil, err
	}

	claims, ok := token.Claims.(*CustomClaims)
	if !ok || !token.Valid {
		return nil, errors.New("token tidak valid atau sudah kadaluwarsa")
	}

	return claims, nil
}
